export type NeonFontCategory = "script" | "display" | "sans" | "slab" | "hand";

export interface NeonFont {
  id: string;
  label: string;
  family: string;
  google: string;
  category: NeonFontCategory;
}

type Stack = "cursive" | "sans-serif" | "serif" | "monospace";

function f(
  id: string,
  google: string,
  category: NeonFontCategory,
  stack: Stack = "sans-serif"
): NeonFont {
  return {
    id,
    label: google,
    google,
    family: `'${google}', ${stack}`,
    category,
  };
}

/**
 * Popular Google Fonts for neon builder (~180).
 * Loaded on demand (hover/select) — never all at once.
 */
export const NEON_FONTS: NeonFont[] = [
  // Script
  f("pacifico", "Pacifico", "script", "cursive"),
  f("great-vibes", "Great Vibes", "script", "cursive"),
  f("dancing-script", "Dancing Script", "script", "cursive"),
  f("satisfy", "Satisfy", "script", "cursive"),
  f("allura", "Allura", "script", "cursive"),
  f("sacramento", "Sacramento", "script", "cursive"),
  f("alex-brush", "Alex Brush", "script", "cursive"),
  f("yellowtail", "Yellowtail", "script", "cursive"),
  f("cookie", "Cookie", "script", "cursive"),
  f("kaushan", "Kaushan Script", "script", "cursive"),
  f("lobster", "Lobster", "script", "cursive"),
  f("lobster-two", "Lobster Two", "script", "cursive"),
  f("courgette", "Courgette", "script", "cursive"),
  f("marck", "Marck Script", "script", "cursive"),
  f("parisienne", "Parisienne", "script", "cursive"),
  f("mrs-saint", "Mrs Saint Delafield", "script", "cursive"),
  f("tangerine", "Tangerine", "script", "cursive"),
  f("pinyon", "Pinyon Script", "script", "cursive"),
  f("italianno", "Italianno", "script", "cursive"),
  f("rouge-script", "Rouge Script", "script", "cursive"),
  f("style-script", "Style Script", "script", "cursive"),
  f("whisper", "Whisper", "script", "cursive"),
  f("birthstone", "Birthstone", "script", "cursive"),
  f("carattere", "Carattere", "script", "cursive"),
  f("imperial", "Imperial Script", "script", "cursive"),
  f("meow-script", "Meow Script", "script", "cursive"),
  f("mr-dafoe", "Mr Dafoe", "script", "cursive"),
  f("norican", "Norican", "script", "cursive"),
  f("oleo", "Oleo Script", "script", "cursive"),
  f("petit-formal", "Petit Formal Script", "script", "cursive"),
  f("damion", "Damion", "script", "cursive"),
  f("homemade-apple", "Homemade Apple", "script", "cursive"),
  f("cedarville", "Cedarville Cursive", "script", "cursive"),
  f("clicker", "Clicker Script", "script", "cursive"),
  f("ephesis", "Ephesis", "script", "cursive"),
  f("euphoria", "Euphoria Script", "script", "cursive"),
  f("fondamento", "Fondamento", "script", "cursive"),
  f("grand-hotel", "Grand Hotel", "script", "cursive"),
  f("sofia", "Sofia", "script", "cursive"),
  f("yesteryear", "Yesteryear", "script", "cursive"),
  f("rochester", "Rochester", "script", "cursive"),
  f("rancho", "Rancho", "script", "cursive"),
  f("niconne", "Niconne", "script", "cursive"),
  f("montez", "Montez", "script", "cursive"),
  f("meddon", "Meddon", "script", "cursive"),
  f("bilbo", "Bilbo Swash Caps", "script", "cursive"),
  f("arizonia", "Arizonia", "script", "cursive"),
  f("aguafina", "Aguafina Script", "script", "cursive"),
  f("alexandra", "Alexandria", "script", "sans-serif"),
  f("berkshire", "Berkshire Swash", "script", "cursive"),
  f("charm", "Charm", "script", "cursive"),
  f("charmonman", "Charmonman", "script", "cursive"),
  f("dynalight", "Dynalight", "script", "cursive"),
  f("festive", "Festive", "script", "cursive"),
  f("herr-von", "Herr Von Muellerhoff", "script", "cursive"),
  f("jim-nightshade", "Jim Nightshade", "script", "cursive"),
  f("kristi", "Kristi", "script", "cursive"),
  f("la-belle", "La Belle Aurore", "script", "cursive"),
  f("mr-de-haviland", "Mr De Haviland", "script", "cursive"),
  f("mrs-sheppards", "Mrs Sheppards", "script", "cursive"),
  f("qwigley", "Qwigley", "script", "cursive"),
  f("seaweed", "Seaweed Script", "script", "cursive"),
  f("stalemate", "Stalemate", "script", "cursive"),
  f("waterfall", "Waterfall", "script", "cursive"),

  // Display
  f("monoton", "Monoton", "display", "cursive"),
  f("bungee", "Bungee", "display", "cursive"),
  f("bungee-shade", "Bungee Shade", "display", "cursive"),
  f("bungee-inline", "Bungee Inline", "display", "cursive"),
  f("bungee-outline", "Bungee Outline", "display", "cursive"),
  f("righteous", "Righteous", "display", "cursive"),
  f("bebas", "Bebas Neue", "display", "sans-serif"),
  f("anton", "Anton", "display", "sans-serif"),
  f("oswald", "Oswald", "display", "sans-serif"),
  f("archivo-black", "Archivo Black", "display", "sans-serif"),
  f("black-ops", "Black Ops One", "display", "cursive"),
  f("orbitron", "Orbitron", "display", "sans-serif"),
  f("audiowide", "Audiowide", "display", "cursive"),
  f("russo", "Russo One", "display", "sans-serif"),
  f("press-start", "Press Start 2P", "display", "cursive"),
  f("silkscreen", "Silkscreen", "display", "cursive"),
  f("alfa-slab", "Alfa Slab One", "display", "cursive"),
  f("bangers", "Bangers", "display", "cursive"),
  f("bowlby", "Bowlby One SC", "display", "cursive"),
  f("cabin-sketch", "Cabin Sketch", "display", "cursive"),
  f("carter-one", "Carter One", "display", "cursive"),
  f("chewy", "Chewy", "display", "cursive"),
  f("coiny", "Coiny", "display", "cursive"),
  f("creepster", "Creepster", "display", "cursive"),
  f("faster-one", "Faster One", "display", "cursive"),
  f("fontdiner", "Fontdiner Swanky", "display", "cursive"),
  f("fredoka", "Fredoka", "display", "sans-serif"),
  f("fugaz", "Fugaz One", "display", "cursive"),
  f("graduate", "Graduate", "display", "cursive"),
  f("knewave", "Knewave", "display", "cursive"),
  f("lemon", "Lemon", "display", "cursive"),
  f("lilita", "Lilita One", "display", "cursive"),
  f("luckiest-guy", "Luckiest Guy", "display", "cursive"),
  f("megrim", "Megrim", "display", "cursive"),
  f("nosifer", "Nosifer", "display", "cursive"),
  f("passion-one", "Passion One", "display", "cursive"),
  f("paytone", "Paytone One", "display", "sans-serif"),
  f("poiret", "Poiret One", "display", "cursive"),
  f("racing-sans", "Racing Sans One", "display", "cursive"),
  f("rammetto", "Rammetto One", "display", "cursive"),
  f("ribeye", "Ribeye", "display", "cursive"),
  f("rubik-mono", "Rubik Mono One", "display", "sans-serif"),
  f("rye", "Rye", "display", "cursive"),
  f("sansita", "Sansita", "display", "sans-serif"),
  f("shrikhand", "Shrikhand", "display", "cursive"),
  f("sigmar", "Sigmar One", "display", "cursive"),
  f("special-elite", "Special Elite", "display", "cursive"),
  f("staatliches", "Staatliches", "display", "cursive"),
  f("titan-one", "Titan One", "display", "cursive"),
  f("ultra", "Ultra", "display", "cursive"),
  f("vt323", "VT323", "display", "monospace"),
  f("wallpoet", "Wallpoet", "display", "cursive"),
  f("wendy-one", "Wendy One", "display", "sans-serif"),
  f("yatra", "Yatra One", "display", "cursive"),
  f("fascinate", "Fascinate Inline", "display", "cursive"),
  f("limelight", "Limelight", "display", "cursive"),
  f("diplomata", "Diplomata", "display", "cursive"),
  f("fredericka", "Fredericka the Great", "display", "cursive"),
  f("stardos", "Stardos Stencil", "display", "cursive"),
  f("syncopate", "Syncopate", "display", "sans-serif"),
  f("teko", "Teko", "display", "sans-serif"),
  f("exo-2", "Exo 2", "display", "sans-serif"),
  f("rajdhani", "Rajdhani", "display", "sans-serif"),
  f("quantico", "Quantico", "display", "sans-serif"),
  f("chakra", "Chakra Petch", "display", "sans-serif"),
  f("oxanium", "Oxanium", "display", "sans-serif"),
  f("saira-stencil", "Saira Stencil One", "display", "cursive"),
  f("big-shoulders", "Big Shoulders Display", "display", "cursive"),
  f("tilt-neon", "Tilt Neon", "display", "cursive"),
  f("tilt-warp", "Tilt Warp", "display", "cursive"),
  f("bagel-fat", "Bagel Fat One", "display", "cursive"),
  f("barriecito", "Barriecito", "display", "cursive"),
  f("iceberg", "Iceberg", "display", "cursive"),
  f("eater", "Eater", "display", "cursive"),
  f("smokum", "Smokum", "display", "cursive"),
  f("ranga", "Ranga", "display", "cursive"),
  f("bowlby-one", "Bowlby One", "display", "cursive"),
  f("bungee-spice", "Bungee Spice", "display", "cursive"),
  f("climate-crisis", "Climate Crisis", "display", "cursive"),
  f("concert-one", "Concert One", "display", "cursive"),
  f("days-one", "Days One", "display", "sans-serif"),
  f("dokdo", "Dokdo", "display", "cursive"),
  f("fascinate-plain", "Fascinate", "display", "cursive"),
  f("finger-paint", "Finger Paint", "display", "cursive"),
  f("flamenco", "Flamenco", "display", "cursive"),
  f("fruktur", "Fruktur", "display", "cursive"),
  f("geostar", "Geostar", "display", "cursive"),
  f("kelly-slab", "Kelly Slab", "display", "cursive"),
  f("lalezar", "Lalezar", "display", "cursive"),
  f("lobster-display", "Modak", "display", "cursive"),
  f("monda", "Monda", "display", "sans-serif"),
  f("pirata", "Pirata One", "display", "cursive"),
  f("plaster", "Plaster", "display", "cursive"),
  f("protest-riot", "Protest Riot", "display", "cursive"),
  f("protest-strike", "Protest Strike", "display", "cursive"),
  f("rubik-dirt", "Rubik Dirt", "display", "cursive"),
  f("rubik-glitch", "Rubik Glitch", "display", "cursive"),
  f("rubik-wet-paint", "Rubik Wet Paint", "display", "cursive"),
  f("rubik-moonrocks", "Rubik Moonrocks", "display", "cursive"),
  f("sixtyfour", "Sixtyfour", "display", "cursive"),
  f("tour-bubble", "Text Me One", "display", "sans-serif"),
  f("unlock", "Unlock", "display", "cursive"),

  // Sans
  f("inter", "Inter", "sans"),
  f("poppins", "Poppins", "sans"),
  f("montserrat", "Montserrat", "sans"),
  f("raleway", "Raleway", "sans"),
  f("nunito", "Nunito", "sans"),
  f("rubik", "Rubik", "sans"),
  f("dm-sans", "DM Sans", "sans"),
  f("outfit", "Outfit", "sans"),
  f("space-grotesk", "Space Grotesk", "sans"),
  f("manrope", "Manrope", "sans"),
  f("figtree", "Figtree", "sans"),
  f("sora", "Sora", "sans"),
  f("urbanist", "Urbanist", "sans"),
  f("lexend", "Lexend", "sans"),
  f("barlow", "Barlow", "sans"),
  f("roboto", "Roboto", "sans"),
  f("open-sans", "Open Sans", "sans"),
  f("lato", "Lato", "sans"),
  f("source-sans", "Source Sans 3", "sans"),
  f("nunito-sans", "Nunito Sans", "sans"),
  f("work-sans", "Work Sans", "sans"),
  f("mulish", "Mulish", "sans"),
  f("karla", "Karla", "sans"),
  f("cabin", "Cabin", "sans"),
  f("josefin", "Josefin Sans", "sans"),
  f("quicksand", "Quicksand", "sans"),
  f("comfortaa", "Comfortaa", "sans"),
  f("asap", "Asap", "sans"),
  f("exo", "Exo", "sans"),
  f("fira-sans", "Fira Sans", "sans"),
  f("ibm-plex", "IBM Plex Sans", "sans"),
  f("noto-sans", "Noto Sans", "sans"),
  f("pt-sans", "PT Sans", "sans"),
  f("ubuntu", "Ubuntu", "sans"),
  f("varela", "Varela Round", "sans"),
  f("maven", "Maven Pro", "sans"),
  f("overpass", "Overpass", "sans"),
  f("prompt", "Prompt", "sans"),
  f("red-hat", "Red Hat Display", "sans"),
  f("albert", "Albert Sans", "sans"),
  f("plus-jakarta", "Plus Jakarta Sans", "sans"),
  f("onest", "Onest", "sans"),
  f("instrument-sans", "Instrument Sans", "sans"),
  f("public-sans", "Public Sans", "sans"),
  f("archivo", "Archivo", "sans"),
  f("be-vietnam", "Be Vietnam Pro", "sans"),
  f("catamaran", "Catamaran", "sans"),
  f("chivo", "Chivo", "sans"),
  f("encode", "Encode Sans", "sans"),
  f("epilogue", "Epilogue", "sans"),
  f("heebo", "Heebo", "sans"),
  f("hind", "Hind", "sans"),
  f("jost", "Jost", "sans"),
  f("kanit", "Kanit", "sans"),
  f("saira", "Saira", "sans"),
  f("signika", "Signika", "sans"),
  f("titillium", "Titillium Web", "sans"),
  f("yantramanav", "Yantramanav", "sans"),
  f("zen-kaku", "Zen Kaku Gothic New", "sans"),
  f("dm-mono", "DM Mono", "sans", "monospace"),
  f("space-mono", "Space Mono", "sans", "monospace"),
  f("jetbrains", "JetBrains Mono", "sans", "monospace"),
  f("inconsolata", "Inconsolata", "sans", "monospace"),
  f("barlow-condensed", "Barlow Condensed", "sans"),
  f("barlow-semi", "Barlow Semi Condensed", "sans"),
  f("cairo", "Cairo", "sans"),
  f("commissioner", "Commissioner", "sans"),
  f("gabarito", "Gabarito", "sans"),
  f("geist", "Geist", "sans"),
  f("host-grotesk", "Host Grotesk", "sans"),
  f("martel-sans", "Martel Sans", "sans"),
  f("radio-canada", "Radio Canada", "sans"),
  f("readex", "Readex Pro", "sans"),
  f("redhat-text", "Red Hat Text", "sans"),
  f("sen", "Sen", "sans"),
  f("sofia-sans", "Sofia Sans", "sans"),
  f("spline-sans", "Spline Sans", "sans"),
  f("wix-madefor", "Wix Madefor Display", "sans"),
  f("ysabeau", "Ysabeau Office", "sans"),

  // Slab / serif
  f("roboto-slab", "Roboto Slab", "slab", "serif"),
  f("playfair", "Playfair Display", "slab", "serif"),
  f("abril", "Abril Fatface", "slab", "serif"),
  f("crete", "Crete Round", "slab", "serif"),
  f("zilla", "Zilla Slab", "slab", "serif"),
  f("arvo", "Arvo", "slab", "serif"),
  f("bitter", "Bitter", "slab", "serif"),
  f("libre-baskerville", "Libre Baskerville", "slab", "serif"),
  f("cormorant", "Cormorant Garamond", "slab", "serif"),
  f("cinzel", "Cinzel", "slab", "serif"),
  f("merriweather", "Merriweather", "slab", "serif"),
  f("lora", "Lora", "slab", "serif"),
  f("crimson", "Crimson Text", "slab", "serif"),
  f("eb-garamond", "EB Garamond", "slab", "serif"),
  f("source-serif", "Source Serif 4", "slab", "serif"),
  f("noto-serif", "Noto Serif", "slab", "serif"),
  f("pt-serif", "PT Serif", "slab", "serif"),
  f("spectral", "Spectral", "slab", "serif"),
  f("cardo", "Cardo", "slab", "serif"),
  f("cormorant-infant", "Cormorant Infant", "slab", "serif"),
  f("domine", "Domine", "slab", "serif"),
  f("faustina", "Faustina", "slab", "serif"),
  f("frank-ruhl", "Frank Ruhl Libre", "slab", "serif"),
  f("ibm-plex-serif", "IBM Plex Serif", "slab", "serif"),
  f("josefin-slab", "Josefin Slab", "slab", "serif"),
  f("libre-caslon", "Libre Caslon Text", "slab", "serif"),
  f("literata", "Literata", "slab", "serif"),
  f("noticia", "Noticia Text", "slab", "serif"),
  f("old-standard", "Old Standard TT", "slab", "serif"),
  f("prata", "Prata", "slab", "serif"),
  f("rozha", "Rozha One", "slab", "serif"),
  f("rufina", "Rufina", "slab", "serif"),
  f("slabo", "Slabo 27px", "slab", "serif"),
  f("vollkorn", "Vollkorn", "slab", "serif"),
  f("young-serif", "Young Serif", "slab", "serif"),
  f("instrument-serif", "Instrument Serif", "slab", "serif"),
  f("fraunces", "Fraunces", "slab", "serif"),
  f("newsreader", "Newsreader", "slab", "serif"),
  f("alegreya", "Alegreya", "slab", "serif"),
  f("alegreya-sc", "Alegreya SC", "slab", "serif"),
  f("bio-rhyme", "BioRhyme", "slab", "serif"),
  f("bodoni", "Bodoni Moda", "slab", "serif"),
  f("bree-serif", "Bree Serif", "slab", "serif"),
  f("cormorant-sc", "Cormorant SC", "slab", "serif"),
  f("cormorant-unicase", "Cormorant Unicase", "slab", "serif"),
  f("dm-serif", "DM Serif Display", "slab", "serif"),
  f("dm-serif-text", "DM Serif Text", "slab", "serif"),
  f("gelasio", "Gelasio", "slab", "serif"),
  f("gentium", "Gentium Book Plus", "slab", "serif"),
  f("gilda", "Gilda Display", "slab", "serif"),
  f("glegoo", "Glegoo", "slab", "serif"),
  f("gorditas", "Gorditas", "slab", "serif"),
  f("grenze", "Grenze Gotisch", "slab", "serif"),
  f("im-fell", "IM Fell English", "slab", "serif"),
  f("kalnia", "Kalnia", "slab", "serif"),
  f("libre-bodoni", "Libre Bodoni", "slab", "serif"),
  f("martel", "Martel", "slab", "serif"),
  f("mate", "Mate", "slab", "serif"),
  f("neuton", "Neuton", "slab", "serif"),
  f("orpheus", "Oranienbaum", "slab", "serif"),
  f("petrona", "Petrona", "slab", "serif"),
  f("playfair-sc", "Playfair Display SC", "slab", "serif"),
  f("questrial", "Questrial", "slab", "sans-serif"),
  f("radley", "Radley", "slab", "serif"),
  f("scope-one", "Scope One", "slab", "serif"),
  f("sorts-mill", "Sorts Mill Goudy", "slab", "serif"),
  f("trirong", "Trirong", "slab", "serif"),
  f("unna", "Unna", "slab", "serif"),
  f("vidaloka", "Vidaloka", "slab", "serif"),
  f("vollkorn-sc", "Vollkorn SC", "slab", "serif"),

  // Hand
  f("caveat", "Caveat", "hand", "cursive"),
  f("shadows", "Shadows Into Light", "hand", "cursive"),
  f("indie-flower", "Indie Flower", "hand", "cursive"),
  f("amatic", "Amatic SC", "hand", "cursive"),
  f("patrick", "Patrick Hand", "hand", "cursive"),
  f("architects", "Architects Daughter", "hand", "cursive"),
  f("kalam", "Kalam", "hand", "cursive"),
  f("handlee", "Handlee", "hand", "cursive"),
  f("gloria", "Gloria Hallelujah", "hand", "cursive"),
  f("rock-salt", "Rock Salt", "hand", "cursive"),
  f("covered-by", "Covered By Your Grace", "hand", "cursive"),
  f("coming-soon", "Coming Soon", "hand", "cursive"),
  f("crafty-girls", "Crafty Girls", "hand", "cursive"),
  f("gochi", "Gochi Hand", "hand", "cursive"),
  f("just-another", "Just Another Hand", "hand", "cursive"),
  f("neucha", "Neucha", "hand", "cursive"),
  f("nothing-you", "Nothing You Could Do", "hand", "cursive"),
  f("patrick-sc", "Patrick Hand SC", "hand", "cursive"),
  f("permanent-marker", "Permanent Marker", "hand", "cursive"),
  f("reenie", "Reenie Beanie", "hand", "cursive"),
  f("schoolbell", "Schoolbell", "hand", "cursive"),
  f("short-stack", "Short Stack", "hand", "cursive"),
  f("swanky", "Swanky and Moo Moo", "hand", "cursive"),
  f("waiting", "Waiting for the Sunrise", "hand", "cursive"),
  f("walter", "Walter Turncoat", "hand", "cursive"),
  f("annie", "Annie Use Your Telescope", "hand", "cursive"),
  f("bad-script", "Bad Script", "hand", "cursive"),
  f("calligraffitti", "Calligraffitti", "hand", "cursive"),
  f("cherry-cream", "Cherry Cream Soda", "hand", "cursive"),
  f("comic-neue", "Comic Neue", "hand", "cursive"),
  f("delius", "Delius", "hand", "cursive"),
  f("gaegu", "Gaegu", "hand", "cursive"),
  f("happymonkey", "Happy Monkey", "hand", "cursive"),
  f("just-me", "Just Me Again Down Here", "hand", "cursive"),
  f("loved-by", "Loved by the King", "hand", "cursive"),
  f("over-the-rainbow", "Over the Rainbow", "hand", "cursive"),
  f("pangolin", "Pangolin", "hand", "cursive"),
  f("shadows-two", "Shadows Into Light Two", "hand", "cursive"),
  f("sue-ellen", "Sue Ellen Francisco", "hand", "cursive"),
  f("the-girl", "The Girl Next Door", "hand", "cursive"),
  f("zeyada", "Zeyada", "hand", "cursive"),
  f("give-you-glory", "Give You Glory", "hand", "cursive"),
  f("homemade", "Homemade Apple", "hand", "cursive"),
  f("klee", "Klee One", "hand", "cursive"),
  f("nanum-pen", "Nanum Pen Script", "hand", "cursive"),
  f("nanum-brush", "Nanum Brush Script", "hand", "cursive"),
  f("shantell", "Shantell Sans", "hand", "cursive"),
  f("spicy-rice", "Spicy Rice", "hand", "cursive"),
];

const loaded = new Set<string>();

export function getNeonFont(id: string): NeonFont {
  return NEON_FONTS.find((x) => x.id === id) || NEON_FONTS[0]!;
}

/** Inject Google Fonts stylesheet once per family. */
export function loadNeonGoogleFont(fontItem: NeonFont): void {
  if (typeof document === "undefined") return;
  if (loaded.has(fontItem.google)) return;
  loaded.add(fontItem.google);
  const elId = `neon-gf-${fontItem.id}`;
  if (document.getElementById(elId)) return;
  const link = document.createElement("link");
  link.id = elId;
  link.rel = "stylesheet";
  link.href = `https://fonts.googleapis.com/css2?family=${encodeURIComponent(fontItem.google).replace(/%20/g, "+")}:wght@400;700&display=swap`;
  document.head.appendChild(link);
}
